name = "iner"
pages_build_output_dir = "cf-deploy"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "iner"
database_id = "a9032961-832f-4502-86c0-cc922521eb9d"

[[kv_namespaces]]
binding = "iner_sessions"
id = "18f4fdaea9bc4199984b85e452ddce1b"